const AJ_PRODUCTS = [

  // ═══ LADIES' BAGS (existing) ═══════════════════════════════════════════════
  { id:1, name:"Black Ribbed Elegance", category:"ladies", subcat:"bags",
    price:38000, image:"images/bag_1.jpeg", sizes:["One Size"],
    badge:"Best Seller", isNew:false,
    description:"Black ribbed structured handbag with dual handles. Bold sophistication meets everyday luxury." },
  { id:2, name:"Checkered Classic", category:"ladies", subcat:"bags",
    price:40000, image:"images/bag_2.jpeg", sizes:["One Size"],
    badge:null, isNew:false,
    description:"Black and cream checkered handbag with premium leather trim. Timeless elegance for every occasion." },
  { id:3, name:"Patchwork Heritage Bag", category:"ladies", subcat:"bags",
    price:42000, image:"images/bag_3.jpeg", sizes:["One Size"],
    badge:"New Arrival", isNew:true,
    description:"Vibrant patchwork handbag with geometric patterns. Truly one of a kind." },
  { id:4, name:"Brown Monogram Tote", category:"ladies", subcat:"bags",
    price:55000, image:"images/bag_4.jpeg", sizes:["One Size"],
    badge:"Premium", isNew:false,
    description:"Brown monogram tote with gold hardware. An iconic statement piece for the woman of distinction." },
  { id:5, name:"Black Bow Mini Bag", category:"ladies", subcat:"bags",
    price:35000, image:"images/bag_5.jpeg", sizes:["One Size"],
    badge:"New Arrival", isNew:true,
    description:"Elegant black mini bag with statement bow detail. Feminine luxury in a compact silhouette." },
  { id:6, name:"Navy Structured Handbag", category:"ladies", subcat:"bags",
    price:45000, image:"images/bag_6.jpeg", sizes:["One Size"],
    badge:null, isNew:false,
    description:"Navy blue structured handbag with silver clasp. Commanding presence, impeccable craft." },
  { id:7, name:"Beige Mini Luxe", category:"ladies", subcat:"bags",
    price:32000, image:"images/bag_7.jpeg", sizes:["One Size"],
    badge:"Best Seller", isNew:false,
    description:"Beige/cream mini bag with ruched handle. Delicate femininity and artisan craftsmanship." },
  { id:8, name:"Ivory Croc Tote", category:"ladies", subcat:"bags",
    price:48000, image:"images/bag_8.jpeg", sizes:["One Size"],
    badge:"Premium", isNew:false,
    description:"Ivory crocodile-embossed structured tote. Exotic texture meets refined elegance." },
  { id:9, name:"Bronze Leopard Handbag", category:"ladies", subcat:"bags",
    price:44000, image:"images/bag_9.jpeg", sizes:["One Size"],
    badge:"New Arrival", isNew:true,
    description:"Brown and gold leopard-textured handbag with dark leather trim. Wild luxury." },
  { id:10, name:"Gunmetal Grace Bag", category:"ladies", subcat:"bags",
    price:50000, image:"images/bag_10.jpeg", sizes:["One Size"],
    badge:"Signature", isNew:false,
    description:"Silver gunmetal metallic structured handbag with crystal accent. Understated opulence." },

  // ═══ MEN'S SANDALS (existing) ══════════════════════════════════════════════
  { id:11, name:"Silver Emblem Slide", category:"shoes",
    price:32000, image:"images/palm_1.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Signature", isNew:false,
    description:"Black leather slide with bold silver emblem detail. A defining signature piece from AJ FOOTZ." },
  { id:12, name:"Olive Suede H-Slide", category:"shoes",
    price:35000, image:"images/palm_2.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Premium", isNew:false,
    description:"Olive green H-cut suede slide with cream sole. Rare craftsmanship for the bold gentleman." },
  { id:13, name:"Taupe H-Strap Slide", category:"shoes",
    price:22000, image:"images/palm_3.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Gray/taupe H-strap slides. Understated sophistication, handmade with top-grain leather." },
  { id:14, name:"Classic Black Thong", category:"shoes",
    price:20000, image:"images/palm_4.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Classic handcrafted black thong sandal. Timeless design and lasting quality." },
  { id:15, name:"Black Crest Slide", category:"shoes",
    price:30000, image:"images/palm_5.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Best Seller", isNew:false,
    description:"Black textured slide with gold crest emblem. Handcrafted luxury for the man who commands attention." },
  { id:16, name:"Black H-Suede Slide", category:"shoes",
    price:28000, image:"images/palm_6.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Black H-cut suede slide with cream sole. Clean, minimal, crafted for the modern gentleman." },
  { id:17, name:"Executive Black Thong", category:"shoes",
    price:25000, image:"images/palm_7.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Best Seller", isNew:false,
    description:"Black thong sandal with signature gold buckle. Premium leather for the man who steps with purpose." },
  { id:18, name:"Carbon Slide", category:"shoes",
    price:27000, image:"images/palm_8.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Black carbon-textured slide with silver oval hardware. Sleek, modern, built for the distinguished man." },
  { id:19, name:"Monogram Cross-Strap", category:"shoes",
    price:33000, image:"images/palm_9.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Black monogram cross-strap sandal with interlocked pattern straps. Street luxury at its finest." },
  { id:20, name:"Oblique Cross-Strap", category:"shoes",
    price:33000, image:"images/palm_10.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Black oblique cross-strap patterned slide. Bold artisan design for the style-forward man." },
  { id:21, name:"Brown Cross-Strap Slide", category:"shoes",
    price:28000, image:"images/palm_11.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Brown and tan cross-strap slide handcrafted from genuine leather." },
  { id:22, name:"Grey Croc H-Slide", category:"shoes",
    price:36000, image:"images/palm_12.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Premium", isNew:false,
    description:"Grey crocodile-embossed H-cut slide. Exotic texture and refined silhouette." },
  { id:23, name:"Gold H-Buckle Slide", category:"shoes",
    price:38000, image:"images/palm_13.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Signature", isNew:false,
    description:"Black leather slide with polished gold H-buckle. Iconic luxury handcrafted to perfection." },
  { id:24, name:"Black Emblem Thong", category:"shoes",
    price:24000, image:"images/palm_14.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Black thong sandal with circular brand emblem. Clean craftsmanship, all-day comfort." },
  { id:25, name:"Crystal Studded Slide", category:"shoes",
    price:42000, image:"images/palm_15.jpeg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Black slide encrusted with crystal rhinestones. Maximum glamour, handcrafted detail." },

  // ═══ MEN'S SANDALS (new arrivals) ══════════════════════════════════════════
  { id:26, name:"Grey Cross-Strap Elite", category:"shoes",
    price:28000, image:"images/mens/1002747119.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Grey scaled cross-strap slide with cushioned black sole. Refined texture, effortless style." },
  { id:27, name:"Black Leather Cross-Strap", category:"shoes",
    price:25000, image:"images/mens/1002747117.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Clean black cross-strap leather slide with cream sole. Minimal luxury at its best." },
  { id:28, name:"Brown Buckle Cross-Strap", category:"shoes",
    price:30000, image:"images/mens/1002747115.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:true,
    description:"Rich brown textured cross-strap with gold-tone buckle. A gentleman's statement piece." },
  { id:29, name:"Black Ribbed Thong", category:"shoes",
    price:22000, image:"images/mens/1002747116.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Black ribbed thong sandal. Artisan stitching on every strap, precision in every step." },
  { id:30, name:"Black H-Grey Panel Slide", category:"shoes",
    price:34000, image:"images/mens/1002747118.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Black leather H-slide with grey GG-pattern panel. Two-tone luxury for the discerning man." },
  { id:31, name:"Grey H-Cut Textured", category:"shoes",
    price:26000, image:"images/mens/1002747120.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Grey H-cut textured slide. Understated craftsmanship that commands a second look." },
  { id:32, name:"Black Thong Gold Buckle", category:"shoes",
    price:25000, image:"images/mens/1002747111.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Best Seller", isNew:false,
    description:"Classic black thong with gold buckle accent. Handcrafted leather that improves with every wear." },
  { id:33, name:"Black H-Silver Buckle", category:"shoes",
    price:28000, image:"images/mens/1002747112.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Black leather H-slide with silver buckle hardware. Clean lines, premium finish." },
  { id:34, name:"Black Double H-Strap", category:"shoes",
    price:35000, image:"images/mens/1002747113.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Signature", isNew:false,
    description:"Double H-strap black slide with silver crest emblem. A signature AJ FOOTZ statement." },
  { id:35, name:"Carbon Black Oval Slide", category:"shoes",
    price:27000, image:"images/mens/1002747114.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Black carbon-weave slide with silver oval cutout. Modern edge, artisan quality." },
  { id:36, name:"Black H-Dark Buckle", category:"shoes",
    price:28000, image:"images/mens/1002747121.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:null, isNew:false,
    description:"Sleek black H-slide with dark matte buckle. Subtle luxury, handcrafted for the bold." },
  { id:37, name:"White H-Slide Black Sole", category:"shoes",
    price:32000, image:"images/mens/1002747128.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Crisp white leather H-slide on black sole. A statement of contrast — handcrafted in Kaduna." },
  { id:38, name:"Dragon Emboss H-Slide", category:"shoes",
    price:40000, image:"images/mens/1002747123.jpg", sizes:["40","41","42","43","44","45","Custom"],
    badge:"Premium", isNew:false,
    description:"Black H-slide with dramatic dragon-embossed leather. Rare artistry, one-of-a-kind character." },

  // ═══ LADIES' COMBO SETS ═════════════════════════════════════════════════════
  { id:40, name:"Gunmetal & Leopard Set", category:"ladies", subcat:"combo",
    price:65000, image:"images/ladies/1002747110.jpg", sizes:["37","38","39","40","Custom"],
    badge:"Best Seller", isNew:false,
    description:"Gunmetal H-slide paired with rich brown leopard-textured bag. A complete luxury statement set." },
  { id:41, name:"Black Carbon & Bow Set", category:"ladies", subcat:"combo",
    price:58000, image:"images/ladies/1002747109.jpg", sizes:["37","38","39","40","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Black carbon cross-strap slide with matching black bow mini bag. Edgy and elegant." },
  { id:42, name:"Gunmetal & Checkered Set", category:"ladies", subcat:"combo",
    price:62000, image:"images/ladies/1002747102.jpg", sizes:["37","38","39","40","Custom"],
    badge:null, isNew:false,
    description:"Gunmetal H-slide paired with classic checkered plaid bag. Timeless style, two pieces perfected." },
  { id:43, name:"Blue Woven & Navy Set", category:"ladies", subcat:"combo",
    price:68000, image:"images/ladies/1002747103.jpg", sizes:["37","38","39","40","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Blue woven multi-strap slide with navy ostrich-embossed bag. A bold blue luxury combo." },
  { id:44, name:"Camel & Cartelo Set", category:"ladies", subcat:"combo",
    price:72000, image:"images/ladies/1002747105.jpg", sizes:["37","38","39","40","Custom"],
    badge:"Best Seller", isNew:false,
    description:"Camel tan cross-strap slide paired with Cartelo monogram tote. Rich in style, rich in craft." },
  { id:45, name:"Silver Bow & Dark Bag Set", category:"ladies", subcat:"combo",
    price:70000, image:"images/ladies/1002747089.jpg", sizes:["37","38","39","40","Custom"],
    badge:"Signature", isNew:false,
    description:"Silver bow rhinestone slide with gunmetal structured bag. Evening glamour, perfectly matched." },
  { id:46, name:"Burgundy & Patchwork Set", category:"ladies", subcat:"combo",
    price:60000, image:"images/ladies/1002747098.jpg", sizes:["37","38","39","40","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Burgundy plain slide with vibrant patchwork geometric bag. Color, culture, and craft in one set." },

  // ═══ LADIES' SOLO SLIDES ════════════════════════════════════════════════════
  { id:50, name:"Camel Cross-Strap Slide", category:"ladies", subcat:"slide",
    price:22000, image:"images/ladies/1002747095.jpg", sizes:["37","38","39","40","Custom"],
    badge:null, isNew:false,
    description:"Warm camel tan cross-strap ladies slide. Handcrafted with soft leather for all-day comfort." },
  { id:51, name:"Silver Bow Slide", category:"ladies", subcat:"slide",
    price:28000, image:"images/ladies/1002747092.jpg", sizes:["37","38","39","40","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Silver metallic bow slide with crystal strap detail. Party-ready glamour, handcrafted elegance." },
  { id:52, name:"Navy H-Cut Slide", category:"ladies", subcat:"slide",
    price:24000, image:"images/ladies/1002747093.jpg", sizes:["37","38","39","40","Custom"],
    badge:null, isNew:false,
    description:"Navy blue H-cut ladies slide. Bold color, clean silhouette, artisan craftsmanship." },
  { id:53, name:"Olive Gold Buckle Slide", category:"ladies", subcat:"slide",
    price:26000, image:"images/ladies/1002747108.jpg", sizes:["37","38","39","40","Custom"],
    badge:"Premium", isNew:false,
    description:"Olive leather double-strap slide with gold buckle. A luxurious everyday piece." },
  { id:54, name:"Black Plain Slide", category:"ladies", subcat:"slide",
    price:20000, image:"images/ladies/1002747097.jpg", sizes:["37","38","39","40","Custom"],
    badge:null, isNew:false,
    description:"Clean black single-strap ladies slide. Minimalist perfection, handcrafted from premium leather." },
  { id:55, name:"Black Rhinestone Thong", category:"ladies", subcat:"slide",
    price:30000, image:"images/ladies/1002747088.jpg", sizes:["37","38","39","40","Custom"],
    badge:"Signature", isNew:false,
    description:"Black thong sandal with crystal rhinestone V-strap. Step into the spotlight." },
  { id:56, name:"Floral Print Slide", category:"ladies", subcat:"slide",
    price:25000, image:"images/ladies/1002747094.jpg", sizes:["37","38","39","40","Custom"],
    badge:"New Arrival", isNew:true,
    description:"White multi-print floral slide with gold chain strap. Vibrant, bold and beautifully handmade." },

  // ═══ COUPLES COLLECTION ═════════════════════════════════════════════════════
  { id:70, name:"Black Carbon Couple Set", category:"couples",
    price:55000, image:"images/couples/1002747125.jpg",
    sizes:["Select Sizes Below"],
    hisSize:["40","41","42","43","44","45","Custom"],
    herSize:["37","38","39","40","Custom"],
    badge:"Best Seller", isNew:false,
    description:"Matching his-and-hers black carbon H-slides. One style, two sizes, perfect pair." },
  { id:71, name:"Cream Croc Couple Set", category:"couples",
    price:60000, image:"images/couples/1002747126.jpg",
    sizes:["Select Sizes Below"],
    hisSize:["40","41","42","43","44","45","Custom"],
    herSize:["37","38","39","40","Custom"],
    badge:"New Arrival", isNew:true,
    description:"Cream croc-embossed matching slides with gold chain detail. Luxury for two." },
  { id:72, name:"Classic Black Couple Set", category:"couples",
    price:52000, image:"images/couples/1002747122.jpg",
    sizes:["Select Sizes Below"],
    hisSize:["40","41","42","43","44","45","Custom"],
    herSize:["37","38","39","40","Custom"],
    badge:null, isNew:false,
    description:"His-and-hers matching black slides. Classic AJ FOOTZ craftsmanship for two." },
  { id:73, name:"Ladies Circle Gift Set", category:"couples",
    price:75000, image:"images/couples/1002747127.jpg",
    sizes:["Select Sizes Below"],
    hisSize:["40","41","42","43","44","45","Custom"],
    herSize:["37","38","39","40","Custom"],
    badge:"New Arrival", isNew:true,
    description:"A full circle of matching ladies slides in every color — the ultimate gift set." },
  { id:74, name:"Cream & Croc Gift Set", category:"couples",
    price:65000, image:"images/couples/1002747124.jpg",
    sizes:["Select Sizes Below"],
    hisSize:["40","41","42","43","44","45","Custom"],
    herSize:["37","38","39","40","Custom"],
    badge:"Premium", isNew:false,
    description:"Cream croc-embossed slide and matching structured bag — the complete gifting set." }
];

function formatPrice(p){ return "₦" + (p||0).toLocaleString("en-NG"); }
function getByCategory(cat){ return cat==="all"?AJ_PRODUCTS:AJ_PRODUCTS.filter(p=>p.category===cat); }
function getNewArrivals(n=4){ return AJ_PRODUCTS.filter(p=>p.isNew).slice(0,n); }
function getFeatured(n=6){ return AJ_PRODUCTS.filter(p=>p.badge).slice(0,n); }
function getMensProducts(){ return AJ_PRODUCTS.filter(p=>p.category==="shoes"); }
function getLadiesProducts(){ return AJ_PRODUCTS.filter(p=>p.category==="ladies"); }
function getCouplesProducts(){ return AJ_PRODUCTS.filter(p=>p.category==="couples"); }
